var dictionary = new Dictionary(_DIC);

dictionary.update({t: ["動詞","接尾"] },{'$set': { t:["助動詞"]} } , { multi:true});
dictionary.update({w: "たがる" },{'$set': { t:["助動詞"]} });

dictionary.remove({w:"呼ばれる"});
dictionary.remove({w:"０"});
dictionary.remove({w:"１"});
dictionary.remove({w:"２"});
dictionary.remove({w:"３"});
dictionary.remove({w:"４"});
dictionary.remove({w:"５"});
dictionary.remove({w:"６"});
dictionary.remove({w:"７"});
dictionary.remove({w:"８"});
dictionary.remove({w:"９"});
dictionary.remove({w:"一"});
dictionary.remove({w:"二"});
dictionary.remove({w:"三"});
dictionary.remove({w:"四"});
dictionary.remove({w:"五"});
dictionary.remove({w:"六"});
dictionary.remove({w:"七"});
dictionary.remove({w:"八"});
dictionary.remove({w:"九"});
dictionary.remove({w:"〇"});
dictionary.remove({w:"，"});
dictionary.remove({w:"．"});
dictionary.remove({w:"十"});
dictionary.remove({w:"百"});
dictionary.remove({w:"千"});
dictionary.remove({w:"万"});
dictionary.remove({w:"億"});
dictionary.remove({w:"兆"});
dictionary.remove({w:"＋"});
dictionary.remove({w:"－"});
dictionary.remove({w:"×"});
dictionary.remove({w:"÷"});
dictionary.remove({w:"√"});
dictionary.remove({w:"、",t:{'$in':["名詞"]}});
